version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  CircleCI:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
          app-dir: ./HabitForge
          # Prevent Git push if tests fail
          post-steps:
            - run:
                name: Prevent Git push if tests failed
                command: |
                  if [[ "${CIRCLE_TEST_RESULT}" != "0" ]]; then
                    echo "Tests failed. Aborting Git push."
                    exit 1
                  fi
      - deploy:
          # Define your Git push steps here
